version: "3.8"
services:
  bot:
    image: chickenspin:v1.0
    env_file: ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database
  database:
    image: postgres:14.1-alpine
    ports:
      - 5434:5432
    restart: always
    command: postgres -c stats_temp_directory=/tmp
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=${DB}
    volumes:
      - "chickenspin-db:/var/lib/postgresql/data"
volumes:
  chickenspin-db:
    external: true
